name: fouadtest
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  pixel_perfect: ^1.1.3
  pix_flutter: ^2.2.0
  country_code_picker: ^3.0.0
  country_picker: ^2.0.23
  country_calling_code_picker: ^2.0.1
  intl_phone_number_input: ^0.7.3+1
  country_pickers: ^2.0.0
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/screens/
  # example:
  fonts:
    - family: AlexandriaFLF
      fonts:
        - asset: assets/fonts/AlexandriaFLF/AlexandriaFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/AlexandriaFLF/AlexandriaFLF-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlexandriaFLF/AlexandriaFLF.ttf

